<template>
  <div>
    <div id="topic">Definitions</div>
    <div id="line"></div>
    <ul>
      <li><strong>Absolute Music</strong>: Pure music, music without a story</li>
      <li><strong>Affection</strong>: The emotion of music</li>
      <li><strong>Answer</strong>: The re-occurrance of the subject, usually in the dominant key</li>
      <li><strong>Aria</strong>: The solo song heard in an opera and an oratorio. Highly emotional</li>
      <li><strong>Art Song</strong>: A song based on a poem, usually has a piano</li>
      <li><strong>Atonality</strong>: The absence of the key</li>
      <li><strong>A Cappella</strong>: Choral music performed without instrumental accompaniment</li>
      <li><strong>Ballet</strong>: A type of dance that often interprets a story</li>
      <li><strong>Baroque</strong>: In Portuguese, it means irregularly shaped or misshapen pearl. First used as a derogatory term in reference to the overly ornate art of the ear. Now applied to art, architecture, and music of the 17th and early 18th centuries</li>
      <li><strong>Bas</strong>: French for "low" indicating a low level of volume (soft). Medieval designation for indoor instruments</li>
      <li><strong>Basso Continuo</strong>: A Baroque performance practice that generally involves two performers. One playing the notated bass line, one realizing the harmonies as indicated by the figured bass. Usually played on a harpsichord or an organ</li>
      <li><strong>Binary Form</strong>: A two-part form (AB)</li>
      <li><strong>Cadenza</strong>: A solo passage in concertos and arias for the soloist to show off their skills. It is usually improvised</li>
      <li><strong>Canon</strong>: Means "law" in Greek. Strict type of polyphonic composition in which each voice enters in succession with the same melody. Canons in which each voice enters on the same pitch are referred to as rounds</li>
      <li><strong>Cantata</strong>: A multi-movement choral work. Sacred or secular. For soloists chorus, and orchestra. Consists of recitatives, arias, ensembles, and choruses</li>
      <li><strong>Cantus Firmus</strong>: Latin for "fixed song". Serves as structural skeleton for a new polyphonic composition. Originally found in the lowest voice</li>
      <li><strong>Castrato</strong>: Male soprano or alto voice. Subjected to a surgical procedure before reaching puberty which prevented the voice from changing. Prominent in 17th and 18th century. Generally used in heroic roles</li>
      <li><strong>Chamber Music</strong>: Music for a small ensemble (2 to 10 players). Usually performed without a conductor</li>
      <li><strong>Changing Meter</strong>: Two or more differnt time signiture within a composition</li>
      <li><strong>Chorale</strong>: A hymn tune, associated with German Protestantism. Inteded for congregational sining, therefore moved mostly by step or narrow leap. Used as the basis for many genres including the cantata. Sometimes adapted from Gregorian chants as well as from other popular sources</li>
      <li><strong>Choreography</strong>: Dance steps and moves</li>
      <li><strong>Chromatic Harmony</strong>: An extensive use of notes outside the prevailing key signature</li>
      <li><strong>Classicism</strong>: The very best construction/composition possible</li>
      <li><strong>Clavichord</strong>: A small rectangular keyboard instrument. Sound is generated by small metal tangents that strike the strings inside the instrument. The application of vibrato to the key produced an expressive sound</li>
      <li><strong>Clavier</strong>: Any type of keyboard</li>
      <li><strong>Coda</strong>: Latin for "tail". A concluding section reaffirming the tonic key</li>
      <li><strong>Col Legno</strong>: Tapping the strings with the wooden part of the bows</li>
      <li><strong>Concertino</strong>: The small group of solo instruments featured in a <em>concerto grosso</em> of the Baroque era</li>
      <li><strong>Concerto</strong>: An instrumental genre for soloist(s) and orchestra. Generally in three movements: fast-slow-fast. Frequently employed ritornello form</li>
      <li><strong>Concerto Grosso</strong>: Baroque orchestral work. Usually in three movements (fast-slow-fast). A group of solo instruments is showcased</li>
      <li><strong>Consort of Instruments</strong>: Renaissance term for instrumental ensemble. Whole consort means all instruments come from one family. Broken consort means a mixed combination of instruments</li>
      <li><strong>Continuous Imitation</strong>: A type of polyphony associated with Renaissance style. A motive or theme is passed from one voice to another. The series of entries can be referred to as "points of imitation". Many motives may receive this treatment within a single work</li>
      <li><strong>Counter Tenor</strong>: High male voice with a strong, pure tone. Often heard in performances of early music</li>
      <li><strong>Counterpoint</strong>: Combination of two or more independent melodic lines</li>
      <li><strong>Countersubject</strong>: A recurring countermelody that accompanies entries of the subject and answer</li>
      <li><strong>Cornetto</strong>: Ancestor of trumpet. Developed from cow horn, later made of wood</li>
      <li><strong>Crumhorn</strong>: Double-reed wind instrument. Sound produced by blowing into enclosed double reed. Usually J-shaped</li>
      <li><strong>Cyclicle Structure</strong>: Materials heard in one movement recurs in later movements</li>
      <li><strong>Da Capo Aria</strong>: An aria with a ternary structure</li>
      <li><strong>Development</strong>: A manipulated version of the theme heard in the second main section of the sonata form</li>
      <li><strong>Dies Irae</strong>: Drawn from Roman Catholic Requiem. Part of the mass</li>
      <li><strong>Double Exposition</strong>: Used in the first movement of a Classical concerto. Orchestral exposition introduces the principal themes and establishes the tnoic key. SOlo exposition follows, during which the soloist, supported by the orchestra, restates the first theme and initiates the modulation away from the tonic key</li>
      <li><strong>Drone</strong>: Sustained pitch or long held note(s). Provides harmonic support. Common feature in folk music</li>
      <li><strong>Dulcimer</strong>: A popular Medieval string instrument consisting of a wooden soundbox and gut strings. Strings are struck with small hammers/mallets</li>
      <li><strong>Durchkomponiert</strong>: Also know as "Through composed". No repetition for the entire composition</li>
      <li><strong>Episode</strong>: A passage within a fugue where either the subject nor the answer is present. Usually in the middle of the piece</li>
      <li><strong>Equal Temperament</strong>: A method of tuning keyboard instrument where an octave is divided into twelve equal semi-tones</li>
      <li><strong>Estampie</strong>: One of the earliest Medieval dances. Stately character that elaborate body movements. Danced by couples</li>
      <li><strong>Exoticism</strong>: The love of a foreign land or culture evoked through music</li>
      <li><strong>Expanded Tonality</strong>: The use of chromatic harmony while still maintaining the tonal center</li>
      <li><strong>Exposition</strong>: The first main section in sonata form with two contrasting themes</li>
      <li><strong>Fanfare</strong>: A loud ceremonial tune of flourish with brass instruments to herald the arrival of an important person</li>
      <li><strong>Figured Bass</strong>: Numbers placed under the bass line to indicate the chord. The middle voices use them to improvise</li>
      <li><strong>French Overture</strong>: Introduction to an opera or oratorio</li>
      <li><strong>Fugal Texture</strong>: A contrapuntal composition based on the principle of imitation. A theme (referred to as the subject) pervades the entire work, entering in one voice and then another</li>
      <li><strong>Fugue</strong>: A highly structure, imitative composition where a single theme or subject prevails</li>
      <li><strong>Gradual</strong>: Fourth item of the Proper of the Mass, sung in a melismatic style, and performed in a responsorial manner in which soloists alternate with a choir</li>
      <li><strong>Gravicembalo</strong>: Italian term for harpsichord</li>
      <li><strong>Gregorian Chant</strong>: A form of plainchant. Modal, monophonic melodies with unmeasured rhythm. Sacred, liturgical music of Roman Catholic Church that implments Latin texts</li>
      <li><strong>Ground Bass</strong>: Baroque compositional device. Consist of the continuous repetition of a short melody over which free variations occur. It often provides the basic structure of a Baroque aria</li>
      <li><strong>Guitarra Moresca</strong>: Guitar of Moorish (North African) origins</li>
      <li><strong>Habanera</strong>: A cuban dance with a tangle rhythm</li>
      <li><strong>Harpsichord</strong>: A keyboard instrument. Sound is generated by small quills inside the instrument that plucked the strings. Often had two manuals (sets of keys)</li>
      <li><strong>Haut</strong>: French for "high" indicating a high level of volume (loud). Medieval designation for outdoor instruments</li>
      <li><strong>Hemiola</strong>: A temporary shift of meter without a change of key signiture</li>
      <li><strong>Heterophonic Texture</strong>: Simultaneous variation; the same melody is played in more than one way at the same time. Involves two or more voices, one playing the original melody while another plays an ornamented or embellished version. Added voices are often improvised</li>
      <li><strong>Homophonic Texture</strong>: A single line of melody supported by a harmonic accompaniment</li>
      <li><strong>Homorhythmic Texture</strong>: In a multi-voiced composition, all voices sing in the same rhythm. A chordal texture (homophonic) results. Coupled with syllabic text setting, this technique delivers the text clearly. The listener's attention is drawn to the top voice</li>
      <li><strong>Hornpipe</strong>: Lively dance in triple meter. English origin. Originally associated with sailors</li>
      <li><strong>Idée Fixe</strong>: A repeated theme with slight changes of key, tone, rhythm, or harmony</li>
      <li><strong>Idiomatic Writing</strong>: A way of composing that takes into account of the individual characters, instruments, and voices</li>
      <li><strong>Impressionism</strong>: Writing music based on visual art. Suggests images rather than directly showing them</li>
      <li><strong>Jazz</strong>: Musical style developed in the U.S. which combines African, European, and pop music. Uses figured bass</li>
      <li><strong>Libretto</strong>: The text of an opera, oratorio, or cantata that is usually written by someone other than the composer</li>
      <li><strong>Lied</strong>: An art song in German. Words are usually taken from German poems</li>
      <li><strong>Lute</strong>: Ancestor of guitar. Plucked, fretted, string instrument. Frequently used to accompany singers</li>
      <li><strong>Mass</strong>: Central service of the Roman Catholic Church</li>
      <li><strong>Mass Ordinary</strong>: Unchanging prayers of the Mass. The components are Kyrie, Gloria, Credo, Sanctus, Benedictus, and Angus Dei</li>
      <li><strong>Mass Proper</strong>: Sections of the Roman Catholic Mass that vary from day to day throughout the church year according to the particular liturgical occasion, as distinct from the Ordinary, in which they remain the same</li>
      <li><strong>Medieval Pipe</strong>: Ancestor of flute. Wind instrument with three holes. Blown through mouthpiece</li>
      <li><strong>Melisma</strong>: A word sung on multiple notes</li>
      <li><strong>Melismatic Text</strong>: Melodic style characterized by many notes sung to a single text syllable. It is the most elaborate and florid form of text setting</li>
      <li><strong>Minuet and Trio</strong>: Ternary form in triple meter. Has a minuet and a trio</li>
      <li><strong>Minimalism</strong>: A style of composition characterized by the repetition and little variation of the music</li>
      <li><strong>Modal Counterpoint</strong>: Polyphonic texture based on modes</li>
      <li><strong>Modal Scales</strong>: A scale that alternate between a whole tone and a semi tone</li>
      <li><strong>Mode</strong>: Scale or sequence of notes used as the basis for a composition; major and minor are modes</li>
      <li><strong>Modified Sonata Form</strong>: An abbreviated sonata form that containes an Exposition and Recapitulation, but no Development. Developed by composers in the 18th century</li>
      <li><strong>Monody</strong>: Literally "one song". A new style which developed in the late 16th century. A single vocal elody with simple instrumental accompaniment. Allowed for greater expression of emotion and clarity of text</li>
      <li><strong>Monophonic Chanson</strong>: Frech for "song". Grew from troubadour tradition. Sometimes performed with accompaniment</li>
      <li><strong>Monophonic Texture</strong>: An unaccompanied melody</li>
      <li><strong>Monothematic Exposition</strong>: In sonata form: Theme 2 is a transposed version of Theme 1</li>
      <li><strong>Motet</strong>: Vocal composition with or without instrumental accompaniment. Usually anonymous and often polytextual in the 13th century</li>
      <li><strong>Motive</strong>: A short rhythm heard in the melody that reappears several times</li>
      <li><strong>Musica Ficta</strong>: Latin for "false music". Performance practice applied in modal music of the late Middle Ages and Renaissance. Performers raised or lowered pitches by chromatic semitone to avoid undersirable intervals. Much like modern-day accidentals</li>
      <li><strong>Musical</strong>: Similar to an opera, but is developed in the U.S. It has spoken diologues, songs and dances, lighting, scenery, and costumes</li>
      <li><strong>Nakers</strong>: Medieval percussion instruments. Played in pairs. Resemble small kettledrums</li>
      <li><strong>Nationalism</strong>: Patriotism expressed through music</li>
      <li><strong>Neumatic Text</strong>: Melodic style with two to four notes set to each syllable</li>
      <li><strong>Neumes</strong>: Early musical notation signs; square notes on a four-line staff</li>
      <li><strong>Opera</strong>: A drama with songs, visual arts, and dance</li>
      <li><strong>Opera Buffa</strong>: Italian comic opera. Sung throughout with no spoken dialogue. Featured down-to-earth characters, fast-paced plots, farce, and secual innuendo</li>
      <li><strong>Opera Seria</strong>: Italian for "serious opera". Sung throughout. Generally based on historical or mythological subjects</li>
      <li><strong>Oratorio</strong>: A large scale work for soloist, chorus, and orchestra. Generally based on biblical texts</li>
      <li><strong>Organum</strong>: Vocal music in which new melodic line(s) are added to an existing Gregorian chant</li>
      <li><strong>Ornamentation</strong>: Decoration to a melodic line. Uses symbols or improvisation</li>
      <li><strong>Ostinato</strong>: A persistent, repeated musical figure or rhythm</li>
      <li><strong>Pedal Point</strong>: A sustained note, usually in the bass</li>
      <li><strong>Pentatonic Scale</strong>: Also know as a 5 notes scale. The 5 black keys on a piano</li>
      <li><strong>Piano Quintet</strong>: Chamber ensemble consisting of piano and four other instruments. Most common grouping is piano with string quartet, though other combinations are possible. Also refers to a composition written for five instruments</li>
      <li><strong>Plainchant</strong>: Monophonic modal melody with a freely flowing, unmeasured vocal line; liturgical chant of the Roman Catholic Church</li>
      <li><strong>Polonaise</strong>: A Polish dance in triple meter transformed by Chopin into a piano composition</li>
      <li><strong>Polyphonic Texture</strong>: A combination of two or more melody lines</li>
      <li><strong>Polyrhythm</strong>: The simultaneous use of two or more conflicting rhythms</li>
      <li><strong>Polytexual Motet</strong>: Two or more texts heard simultaneously. As a result, the words can sometimes be hard to distinguish</li>
      <li><strong>Polytonality</strong>: The simultaneous use of two or more tonal centres</li>
      <li><strong>Portative Organ</strong>: Medieval portable keyboard instrument. Small keyboard activates high-pitched pipes. Sound generated through pumping bellows. Also called <em>organetto</em></li>
      <li><strong>Positive Organ</strong>: Originated in 14th century, but remained popular through the Renaissance. Slightly larger than portative organ, but still portable, like a piece of furniture. Had one keyboard, no pedals, and small pipes</li>
      <li><strong>Prelude</strong>: A short improvised keyboard work. Usually paired with a fugue</li>
      <li><strong>Primitivism</strong>: A belief during the Pagan era in ancient time. Shown through rhythm, strong accents, heavy syncopation, polyrhythms and an expanded percussion section</li>
      <li><strong>Programmatic Writing</strong>: A way of writing with descriptive elements</li>
      <li><strong>Program Music</strong>: Instrumental music with extramusical associations (literary, poetic, visual)</li>
      <li><strong>Program Symphony</strong>: A multi-movement orchestral work with programmatic elements</li>
      <li><strong>Psaltery</strong>: Popular Medieval string instrument. Consisted of a trapezoidal wooden soundbox with gut strings. Strings are plucked with fingers or with a plectrum</li>
      <li><strong>Real Answer</strong>: An exact transposition of the subject</li>
      <li><strong>Rebec</strong>: Medieval indoor instrument. Pear shaped, bowed, string instrument. Has three strings. Played on the arm or under the chin</li>
      <li><strong>Recapitulation</strong>: The third main section in sonata form where the first and second themes are both restated in the tonic</li>
      <li><strong>Recitative</strong>: A speech-like style of singing used in operas, oratorios, and cantatas. Usually used to advance the plot</li>
      <li><strong>Recitativo Accompagnato</strong>: Accompanied recitative</li>
      <li><strong>Recitativo Secco</strong>: Recitative supported by only continuo</li>
      <li><strong>Recorder</strong>: Medieval indoor instrument. End-blown wind instrument; came in different lengths. Had finger holes. Remained popular into Baroque period</li>
      <li><strong>Regal</strong>: 14th-century portable organ. Ancestor of modern harmonium. Had small keyboard and reeds instead of pipes. Like the portative organ, it could be carried by means of a strap around the neck allowing the player to pump the bellows with the left hand while playing on the keyboard with the right hand</li>
      <li><strong>Responsorial Singing</strong>: A method of performance where solo voice alternates with chorus. Solo passages refeered to as "verse". Choral passages referred to as "respond"</li>
      <li><strong>Repieno</strong>: The larger group in a concerto grosso</li>
      <li><strong>Responsorial Singing</strong>: Singing, especially in plainchant, in which a soloist or a group of soloists alternates with the choir</li>
      <li><strong>Ritornello</strong>: A recurring theme that functions as a refrain in Baroque compositions. Can serve as introduction and postlude in arias or choruses or as a unifying thread in concertos</li>
      <li><strong>Ritornello Form</strong>: A passage for full orchestra in concerto that is repeated between ideas of music or between instrumental solo</li>
      <li><strong>Rocket Theme</strong>: A rapidly ascending arpeggio used for the opening</li>
      <li><strong>Romanticism</strong>: Emphasis on creative imagination and expression of emotions</li>
      <li><strong>Rondeau</strong>: A popular fixed poetic form used in the polyphonic chansons of the Ars nova. Consists of four verses with a refrain. The text of the first stanza was repeated partially in the second verse and repeated fully in the fourth verse. (AB aA ab AB)</li>
      <li><strong>Rondo Form</strong>: A classical formal structure. ABACA</li>
      <li><strong>Ronded Binary Form</strong>: A binary form where section A returns at the end. ABA</li>
      <li><strong>Rubato</strong>: A flexable tempo that can speed up and slow down to show expression</li>
      <li><strong>Sackbut</strong>: Ancestor of the trombone</li>
      <li><strong>Scherzo and Trio</strong>: Invented by Beethoven to replace the Minuet and Trio form. It is also in triple meter</li>
      <li><strong>Serenade</strong>: A multi-movement orchestral genre for a small orchestra or chamber ensemble</li>
      <li><strong>Shawm</strong>: Ancestor of oboe. Double reed instrument. Produces shrill nasal tone</li>
      <li><strong>Sonata Cycle</strong>: A multi-movement structure that emerged in the classical era. It is demonstrated in symphony, sonata or concerto</li>
      <li><strong>Sonata Form</strong>: Formal structure often used in the first movement of a sonata cycle. Consist of exposition, development, and recapitulation</li>
      <li><strong>Sonata-Rondo Form</strong>: A mix of sonata form and rondo form (ABACABA)</li>
      <li><strong>Stile Concitato</strong>: Italian for "agitated style". Expresses the "hidden tremors of the soul". Achieved through use of instrumental, ornamentation and rapid repeated notes (vocal)</li>
      <li><strong>Stile Rappresentativo</strong>: Italian for "representational style". A recitative-like moelody moving freely over a foundation of simple chords. The music was meant to heighten the emotional power of the text</li>
      <li><strong>String Quartet</strong>: The most important chamber music genre of the classical era. Consists of first and second violin, viola and cello</li>
      <li><strong>Strophic Form</strong>: A song structure where the same music is performed for each verse of the poem. As a result, little connection can be achieved between the words and music</li>
      <li><strong>Subject</strong>: The initial statement of the main theme of a fugue in the tonic key</li>
      <li><strong>Syllabic Text</strong>: Melodic style with one note to each syllable of text. The text can be heard very clearly in this setting</li>
      <li><strong>Symbolism</strong>: A type of writing music where the author suggests matter rather than depicting it specifically</li>
      <li><strong>Symphonic Poem</strong>: A single movement work that is generally free in form with literary or pictorial associations</li>
      <li><strong>Symphony</strong>: A work featuring a statement of a melody followed by a series of transformations where changes can be made to melody, harmony, rhythm or orchestration, often used in the slow sonata cycle</li>
      <li><strong>Tabor</strong>: Medieval percussion instrument. Large, cylindrical drum</li>
      <li><strong>Tambourine</strong>: Wooden frame with small metal disks inserted. Played by striking or shaking</li>
      <li><strong>Tenor</strong>: The voice that contains the <em>cantus firmus</em></li>
      <li><strong>Ternary Form</strong>: A three-part form (ABA)</li>
      <li><strong>Terzetto</strong>: Italian term for "trio". A musical number for three voices (characters)</li>
      <li><strong>Theme and Variations</strong>: A work featuring a statement of a melody followed by a series of transformations where changes can be made to melody, harmony, rhythm or orchestration</li>
      <li><strong>Tonal Answer</strong>: A statement of the subject in which one or more intervals is adjusted to accommodate the harmony</li>
      <li><strong>Tremolo</strong>: A rapid alternation between two notes or between notes of chord</li>
      <li><strong>Troubadour</strong>: Aristocratic poet-musicians. Composed and performed original poems and songs. Lived and worked in southern France</li>
      <li><strong>Trouser Role</strong>: A male character performed by a soprano, mezzo soprano, or contralto. Roles originally created for male castrati are frequently into trouser roles in modern performances</li>
      <li><strong>Trouvère</strong>: French for "finder" or "inventor". Composed and performed original poems and songs. Song of courtly love</li>
      <li><strong>Verse Chorus Structure</strong>: A common song structure in popular music where verses develop the storyline while the chorus acts as a tuneful refrain</li>
      <li><strong>Vielle</strong>: Medieval ancestor of the violin. The body of the instrument had a figure-eight shape. Played with a bow</li>
      <li><strong>Viennese School</strong>: The musical style of Haydn, Mozart, and Beethoven</li>
      <li><strong>Viol</strong>: Renaissance family of bowed string instruments. Varied in size from small to large</li>
      <li><strong>Viola da Gamba</strong>: An instrument in the viol family. Had six strings. Held between the legs when played, like a modern cello. Fretted like a guitar</li>
      <li><strong>Virginal</strong>: A generic term used in England for all plucked keyboard instruments. Smaller and lighter than the harpsichord, simpler in construction, less expensive. Italian and Flemish virginals came in many shapes; English versions were always rectangular. Could be placed on a tabletop or held in the player's lap</li>
      <li><strong>Whole-Tone Scale</strong>: A scale with notes that are spaced a whole tone apart</li>
      <li><strong>Word Painting</strong>: When music mirrors the literal meaning of the words through melody, harmony, or rhythm</li>
    </ul>
    <br />
  </div>
</template>

<script>
export default {
  name: "MusicHistory",
  metaInfo: {
    title: "Music History",
    meta: [
      { name: "description", content: "A list of all the terms you need to know for Royal Conservatory Music Hisotry Level 9 and 10 and their definitions in alphabetical order." },
      { name: "keywords", content: "music history, definitions, royal conservatory, rcm, grade 9, grade 10, classical, baroque, list, terms" }
    ],
    link: [
      { rel: "canonical", href: "https://www.chingchang.ca/music-history" }
    ]
  }
};
</script>

<style lang="scss" scoped>
ul {
  padding-left: 25px;
  li {
    font-size: 23px;
    list-style-position: outside;
  }
}
</style>