<template>
  <div>
    <div id="topic">Theory of Knowledge</div>
    <div id="date-written">December 29, 2019</div>
    <div id="subtitle">Can the acquisition of knowledge accumulate without a multiplicity of theories?</div>
    <div id="line"></div>
    <picture>
      <source media="(max-width: 414px)" srcset="@/assets/blog/theory-of-knowledge/big-brain-414.jpg" type="image/jpeg" />
      <source srcset="@/assets/blog/theory-of-knowledge/big-brain.jpg" type="image/jpeg" />
      <img id="cover-photo" src="@/assets/blog/theory-of-knowledge/big-brain.jpg" alt="Newton's cradle with lightbulbs" />
    </picture>
    <div id="text">
      <div class="paragraph">
        Okay, you've probably come here to read a blog post. I'm sorry, this is not a blog. This is nothing but my IB TOK Essay. I just posted it here because it is philosophical, which is coherent to my other blog posts. Totally didn't plan to share it here, until I received a 9/10 on it (lost 1 mark for not citing my sources 😭). This is really different from what a usual blog would look like. If you are not into reading 1600 words of tHeOrY oF kNoWlEdGe, please exit and go read my other blog posts before you think all my writings are as boring as this. But if you like random philosophy as much as I do, embrace yourself for 1600 words of nonsense that somehow makes some sense:
      </div>
      <div class="paragraph" style="text-align: center;">
        <strong>“Given that every theory has its limitations, we need to retain a multiplicity of theories to understand the world.” Discuss this claim with reference to two areas of knowledge.</strong>
      </div>
      <div class="paragraph">
        As humanity attempts to understand the world, it is obligatory for us to explore and validate new theories. When acquiring these new theories, we often use coherence truth checks to enforce the validity of such theories. Hence, it is believed that we need to retain a multiplicity of theories to overcome the limitation of each individual theory, in order to acquire theories that help us better understand the world. However, in the areas of knowledge where relativism exists, different theories may contradict each other, and the acquisition of knowledge would therefore accumulate without a multiplicity of theories. While these theories may not be able to be validated using coherence truth checks, they can be validated using pragmatic truth checks. Furthermore, we need to pay close attention in justifying the limitations of each theory. When looking at individual theories that have high limitations, retaining a multiplicity of these theories may still result in higher limitations than having a different theory with low limitations. Therefore, not only do we need to discuss the multiplicity of theories, we need to also consider the limitations of the premises. I will be looking at the areas of knowledge of natural sciences and ethics to determine whether these ideas apply to them.
      </div>
      <div class="paragraph">
        I will be discussing “To what extent are theories concluded by multiple theories more plausible to be considered more pragmatically valid than those concluded by a single theory?” to determine whether retaining a multiplicity of theories is beneficial in pragmatically validating theories that help us understand the world. Given that theories in the area of knowledge of natural science can only be disproved, rather than proved, theories concluded by a single theory are more vulnerable to be pragmatically invalid than theories concluded by multiple theories, because the former is coherent to less theories than the latter, which means that if the theory that it concludes from is disproved, the entire concluded theory would be hypothetical. Whereas the disproving of one theory of the multiple theories that conclude the latter theory would not always completely pragmatically invalidate the concluded theory.
      </div>
      <div class="paragraph">
        When Albert Einstein wrote his field equations for general relativity in 1917, he noticed the inaccuracy in his equation despite having the correct variables. As a result, he proposed that there existed a cosmological constant, which is the energy density of space, that should be put into the equation. The cosmological constant was determined by Einstein with the theories of general relativity and static universe — a cosmological model in which the universe is spatially and temporally infinite, and is neither expanding nor contracting. The presence of this constant was later questioned in 1931, as Edwin Hubble proposed that the universe is not static, but is expanding. Consequently, most physicists believed that there existed no such cosmological constant. However, due to the coherence of the cosmological constant with Einstein’s field equation for general relativity, the theory of this constant was not completely invalidated. Either there exists a cosmological constant, or Einstein’s field equation was wrong. In 1998, it was discovered that the expansion of the universe is accelerating, which suggests that there does exist such a cosmological constant, and is a positive non-zero number. This exemplifies how a theory that is concluded from multiple theories is not necessarily invalid when one of the many theories that it concludes from is proven to be invalid. On the other hand, when a theory is concluded from only one theory, the invalidation of just one theory could make the entire conclusion hypothetical. An example of this is the luminiferous aether theory of light. People believed that light was unable to propagate through a vacuum. Accordingly, they assumed that there existed a space-filling substance or field called the “aether” to propagate light. The luminiferous aether theory was then further used to explain the propagation of electromagnetic and gravitational forces. However, when Michelson Morely disproved the luminiferous aether theory in 1887, the aether explanation for electromagnetic and gravitational forces was immediately debunked. Therefore, theories concluded by a single theory are more vulnerable to be pragmatically invalid than theories concluded by multiple theories. As supported by the examples, a theory concluded from only one theory can be invalidated as long as the theory that it concludes from is invalidated, but theories that are concluded from multiple theories cannot be completely invalidated with the invalidation of only one theory. Thence, we need to retain a multiplicity of theories to understand the world because they help us conclude theories that are more pragmatically valid.
      </div>
      <div class="paragraph">
        On the contrary, in the area of knowledge of ethics, standards are usually formed by a single theory that a person prefers, and the acceptance of a theory usually comes at the expense of rejecting the others. Therefore, theories concluded by multiple theories are pragmatically valid to no extent because retaining a multiplicity of theories causes the corresponding validation to contradict the other theories, which induces a pragmatic discrepancy with personal ethical standards. In a worldwide survey of 2.3 million people called The Moral Machine, people from the Western, Eastern, and Southern sides of the world were prompted with a hypothetical ethical dilemma of who they would spare in an inevitable car crash, if they were the programmers of a self-driving car. As a result, most Eastern people would spare the elderly, most Southern people would spare the children, whereas most Western people would remain inactive. This divergent result reflects that the acquisition of knowledge in ethics is dependent on personal preferences, and is different across the world because of divergent cultural values, which implies that most ethical standards are not universal. If one chooses not to crash into the children because they support the theory that young lives are more valuable, they then automatically reject the theory that old lives are more valuable. Even if the complexity of the dilemma was higher, such as a group of elderly to one child, either choice would reject the theory that the quantitative and qualitative value of the other side is higher. Therefore, one cannot conclude pragmatic ethical theories while retaining a multiplicity of other ethical theories, and thus, we do not need to retain a multiplicity of theories to understand the world of ethical choices.
      </div>
      <div class="paragraph">
        Next, I will be discussing “To what extent does the multiplicity of premises in a syllogism make their limitation lower than the limitation of the theory that they conclude?” to determine the necessity of retaining a multiplicity of theories to overcome the limitations of each individual theory. The conclusion of a theory in syllogism can be made using either inductive or deductive reasoning. When using inductive reasoning, the conclusion must have an equal or higher limitation than the premises. For example, in the area of knowledge of natural science, the premises of “all atoms have at least one proton” and “boron is an atom” can lead us to conclude that boron has at least one proton. In this example, the conclusion has a higher limitation than the premises by stating that boron specifically has at least one proton. Although this shows that retaining a multiplicity of theories helps us conclude more specific theories, it does not help us overcome the limitations of the premises, as the conclusion has a higher limitation. On the other hand, while deductive reasoning helps us overcome the limitations of the premises, unlike inductive reasoning, scientists need to use other theories to explain why the deduced conclusion works. For example, a sample of premises that each state that a specific ionic compound has a high boiling point were put together to conclude that all ionic compounds have high boiling points. However, after the scientists made that conclusion, they went on and explained the phenomenon by stating that ionic compounds have high electrostatic forces of attraction between the oppositely charged ions, hence require more energy to be broken apart. This means that retaining a multiplicity of premises overcomes the limitation of each premise to a limited extent because it does not lead to a lower limitation without the explanation from another scientific theory, and that scientific theory can be used to overcome the limitations without the multiplicity of the premises anyway.
      </div>
      <div class="paragraph">
        Contrarily, in the area of knowledge of ethics, deduced theories do not need to be explained, as long as they are consistently observed. In an experiment where three to six-month-old babies were shown a scene where a puppet is struggling to open a box, and one puppet tries to help, while the other shuts the box closed, more than three quarters of the babies preferred the puppet who helped rather than the one who did the opposite. They then used deductive reasoning to conclude that humans develop positive feelings toward helpful individuals, at as early as three months old. This conclusion was made and accepted without having an explanation, because the phenomenon was consistently observed. Thus, retaining a multiplicity of premises does help us overcome their limitations, and support theories that help us better understand the world.
      </div>
      <div class="paragraph">
        To understand the world, we must continue exploring and validating new theories. In the areas of knowledge with relativism, the multiplicity of theories leads to contradiction and therefore hinders the pragmatic validity of theories. However, in other areas of knowledge, it prevents theories from being disproved, and thus helps us enforce pragmatic validity. Moreover, in areas of knowledge where theories can be validated using only observation, the multiplicity of theories can even assist us in overcoming the limitation of each individual theory, helping us explore new theories.
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "TheoryOfKnowledge",
  metaInfo: {
    title: "Theory of Knowledge",
    meta: [
      { name: "description", content: "We often use coherence truth checks to enforce the validity of newly acquired knowledge. Hence, it is believed that we need to retain a multiplicity of theories." },
      { name: "keywords", content: "IB TOK Essay, exemplar, theory, blog, limitation, multiplicity, science, ethics, The Moral Machine, Ching Chang" }
    ],
    link: [
      { rel: "canonical", href: "https://www.chingchang.dev/blog/theory-of-knowledge" }
    ]
  }
}
</script>